# GitHub Pages Configuration
title: RFP Malwee - Geovendas
description: Resposta TÃ©cnica Completa da Geovendas para a RFP Malwee
theme: null
markdown: kramdown
baseurl: /rfp-malwee
url: https://gab.github.io
